languageCode = "en-us"
baseurl = "http://vikramraman.com"
title = "Vikram Raman"
theme = "hemingway"
copyright = "&copy; Vikram Raman 2018"
googleAnalytics = "UA-81689311-2"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
author = "Vikram Raman"

[params.highlight]
style = "ocean"
languages = ["go", "dockerfile"]

[[params.social]]
url = "http://www.vikramraman.com/about/"
fa_icon = "fa-user"

[[params.social]]
url = "https://github.com/vikramraman"
fa_icon = "fa-github"

[[params.social]]
url = "https://www.linkedin.com/in/ramanvikram"
fa_icon = "fa-linkedin"

[[params.social]]
url = "mailto: vikram.raman@gmail.com"
fa_icon = "fa-envelope"
